/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.view.state.uad.anonymizer;

import com.liferay.frontend.view.state.model.FVSEntry;
import com.liferay.frontend.view.state.service.FVSEntryLocalService;
import com.liferay.frontend.view.state.uad.constants.FVSUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the fvs entry UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link FVSEntryUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseFVSEntryUADAnonymizer
	extends DynamicQueryUADAnonymizer<FVSEntry> {

	@Override
	public void autoAnonymize(
			FVSEntry fvsEntry, long userId, User anonymousUser)
		throws PortalException {

		if (fvsEntry.getUserId() == userId) {
			fvsEntry.setUserId(anonymousUser.getUserId());
			fvsEntry.setUserName(anonymousUser.getFullName());
		}

		fvsEntryLocalService.updateFVSEntry(fvsEntry);
	}

	@Override
	public void delete(FVSEntry fvsEntry) throws PortalException {
		fvsEntryLocalService.deleteFVSEntry(fvsEntry);
	}

	@Override
	public Class<FVSEntry> getTypeClass() {
		return FVSEntry.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return fvsEntryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return FVSUADConstants.USER_ID_FIELD_NAMES_FVS_ENTRY;
	}

	@Reference
	protected FVSEntryLocalService fvsEntryLocalService;

}