/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

const CHECK_AND_FIX_GLOBS = [
	'!settings.json',
	'!tsconfig.json',
	'/{,dxp/}*.{js,ts}',
	'/{,dxp/}apps/*/*/*.{js,json,ts,tsx}',
	'/{,dxp/}apps/*/*/*/*.{js,json,ts,tsx}',
	'/{,dxp/}apps/*/*/*/{src,test}/**/*.{js,scss,ts,tsx}',
	'/{,dxp/}apps/*/*/*/{src}/**/*.{jsp,jspf}',
	'/{,dxp/}apps/*/*/{src,test}/**/*.{js,scss,ts,tsx}',
	'/{,dxp/}apps/*/*/{src}/**/*.{jsp,jspf}',
];

module.exports = {
	check: CHECK_AND_FIX_GLOBS,
	defaults: {
		federation: {
			mode: 'disabled',
			remotes: [
				'frontend-js-components-web',
				'frontend-js-metal-web',
				'frontend-js-react-web',
				'frontend-js-spa-web',
				'frontend-js-web',
				'frontend-taglib',
				'frontend-taglib-chart',
				'frontend-taglib-clay',
			],
			shared: [
				'@clayui/alert',
				'@clayui/autocomplete',
				'@clayui/badge',
				'@clayui/breadcrumb',
				'@clayui/button',
				'@clayui/card',
				'@clayui/charts',
				'@clayui/color-picker',
				'@clayui/css',
				'@clayui/data-provider',
				'@clayui/date-picker',
				'@clayui/drop-down',
				'@clayui/empty-state',
				'@clayui/form',
				'@clayui/icon',
				'@clayui/label',
				'@clayui/layout',
				'@clayui/link',
				'@clayui/list',
				'@clayui/loading-indicator',
				'@clayui/management-toolbar',
				'@clayui/modal',
				'@clayui/multi-select',
				'@clayui/multi-step-nav',
				'@clayui/nav',
				'@clayui/navigation-bar',
				'@clayui/pagination',
				'@clayui/pagination-bar',
				'@clayui/panel',
				'@clayui/popover',
				'@clayui/progress-bar',
				'@clayui/shared',
				'@clayui/slider',
				'@clayui/sticker',
				'@clayui/table',
				'@clayui/tabs',
				'@clayui/time-picker',
				'@clayui/tooltip',
				'@clayui/upper-toolbar',
				'classnames',
				'clay',
				'clay-alert',
				'clay-autocomplete',
				'clay-badge',
				'clay-button',
				'clay-card',
				'clay-card-grid',
				'clay-checkbox',
				'clay-collapse',
				'clay-component',
				'clay-data-provider',
				'clay-dataset-display',
				'clay-dropdown',
				'clay-icon',
				'clay-label',
				'clay-link',
				'clay-list',
				'clay-loading-indicator',
				'clay-management-toolbar',
				'clay-modal',
				'clay-multi-select',
				'clay-navigation-bar',
				'clay-pagination',
				'clay-pagination-bar',
				'clay-portal',
				'clay-progress-bar',
				'clay-radio',
				'clay-select',
				'clay-sticker',
				'clay-table',
				'clay-tooltip',
				'formik',
				'incremental-dom',
				'incremental-dom-string',
				'lodash.escape',
				'lodash.groupby',
				'lodash.isequal',
				'lodash.memoize',
				'lodash.unescape',
				'metal',
				'metal-affix',
				'metal-ajax',
				'metal-anim',
				'metal-aop',
				'metal-assertions',
				'metal-clipboard',
				'metal-component',
				'metal-debounce',
				'metal-dom',
				'metal-drag-drop',
				'metal-events',
				'metal-incremental-dom',
				'metal-jsx',
				'metal-key',
				'metal-keyboard-focus',
				'metal-multimap',
				'metal-pagination',
				'metal-path-parser',
				'metal-position',
				'metal-promise',
				'metal-router',
				'metal-scrollspy',
				'metal-soy',
				'metal-soy-bundle',
				'metal-state',
				'metal-storage',
				'metal-structs',
				'metal-throttle',
				'metal-toggler',
				'metal-uri',
				'metal-useragent',
				'metal-web-component',
				'prop-types',
				'querystring',
				'react',
				'react-dnd',
				'react-dnd-html5-backend',
				'react-dom',
				'svg4everybody',
				'uuid',
				'xss-filters',
			]
		}
	},
	fix: CHECK_AND_FIX_GLOBS,
};
