/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

const CHECK_AND_FIX_GLOBS = [
	'!settings.json',
	'!tsconfig.json',
	'/{,dxp/}*.{js,ts}',
	'/{,dxp/}apps/*/*/*.{js,json,ts,tsx}',
	'/{,dxp/}apps/*/*/*/*.{js,json,ts,tsx}',
	'/{,dxp/}apps/*/*/*/{src,test}/**/*.{js,scss,ts,tsx}',
	'/{,dxp/}apps/*/*/*/{src}/**/*.{jsp,jspf}',
	'/{,dxp/}apps/*/*/{src,test}/**/*.{js,scss,ts,tsx}',
	'/{,dxp/}apps/*/*/{src}/**/*.{jsp,jspf}',
];

module.exports = {
	build: {
		bundler: {
			config: {
				imports: {
					'@liferay/frontend-js-react-web': {
						'/': '>=1.0.0',
						classnames: '>=2.2.6',
						formik: '>=1.4.3',
						'prop-types': '>=15.7.2',
						react: '>=16.8.6',
						'react-dnd': '>=7.0.2',
						'react-dnd-html5-backend': '>=7.0.2',
						'react-dom': '>=16.8.6',
					},
					'@liferay/frontend-taglib': {
						'/': '>=1.0.0',
					},
					'frontend-js-components-web': {
						'/': '>=1.0.0',
					},
					'frontend-js-metal-web': {
						'incremental-dom': '>=0.5.1',
						'incremental-dom-string': '>=0.0.3',
						metal: '>=2.16.5',
						'metal-affix': '>=2.0.0',
						'metal-ajax': '>=2.1.1',
						'metal-anim': '>=2.0.0',
						'metal-aop': '>=3.0.0',
						'metal-assertions': '>=2.16.5',
						'metal-clipboard': '>=2.0.0',
						'metal-component': '>=2.16.5',
						'metal-debounce': '>=2.0.0',
						'metal-dom': '>=2.16.5',
						'metal-drag-drop': '>=3.0.1',
						'metal-events': '>=2.16.5',
						'metal-incremental-dom': '>=2.16.5',
						'metal-jsx': '>=2.16.5',
						'metal-key': '>=1.0.0',
						'metal-keyboard-focus': '>=2.0.1',
						'metal-multimap': '>=2.0.0',
						'metal-pagination': '>=2.0.1',
						'metal-path-parser': '>=1.0.3',
						'metal-position': '>=2.1.1',
						'metal-promise': '>=2.0.1',
						'metal-router': '>=3.6.3',
						'metal-scrollspy': '>=2.0.0',
						'metal-soy': '>=2.16.5',
						'metal-soy-bundle': '>=2.16.5',
						'metal-state': '>=2.16.5',
						'metal-storage': '>=1.1.0',
						'metal-structs': '>=1.0.1',
						'metal-throttle': '>=3.0.0',
						'metal-toggler': '>=2.3.0',
						'metal-uri': '>=2.4.0',
						'metal-useragent': '>=3.0.0',
						'metal-web-component': '>=2.16.5',
						querystring: '>=0.2.0',
						'xss-filters': '>=1.2.7',
					},
					'frontend-js-node-shims': {
						assert: '>=1.4.1',
						buffer: '>=5.0.7',
						console: '>=1.1.0',
						domain: '>=1.1.7',
						events: '>=1.1.1',
						os: '>=0.3.0',
						path: '>=0.0.0',
						process: '>=0.11.10',
						punycode: '>=2.1.0',
						setimmediate: '>=1.0.5',
						string_decoder: '>=1.0.3',
						timers: '>=2.0.4',
						tty: '>=0.0.0',
						url: '>=0.11.0',
						util: '>=0.10.3',
						vm: '>=0.0.4',
					},
					'frontend-js-spa-web': {
						senna: '>=2.6.1',
					},
					'frontend-js-web': {
						'/': '>=1.0.0',
						'@liferay/amd-loader': '>=4.3.1',
						'lodash.escape': '>=4.0.1',
						'lodash.groupby': '>=4.6.0',
						'lodash.isequal': '>=4.5.0',
						'lodash.memoize': '>=4.1.2',
						'lodash.unescape': '>=4.0.1',
						svg4everybody: '>=2.1.9',
						uuid: '>=3.3.2',
					},
					'frontend-taglib-chart': {
						'clay-charts': '>=2.9.0',
					},
					'frontend-taglib-clay': {
						'@clayui/alert': '>=3.0.0',
						'@clayui/autocomplete': '>=3.0.0',
						'@clayui/badge': '>=3.0.0',
						'@clayui/breadcrumb': '>=3.0.0',
						'@clayui/button': '>=3.0.0',
						'@clayui/card': '>=3.0.0',
						'@clayui/charts': '>=3.0.0',
						'@clayui/color-picker': '>=3.0.0',
						'@clayui/css': '>=3.0.0',
						'@clayui/data-provider': '>=3.0.0',
						'@clayui/date-picker': '>=3.0.0',
						'@clayui/drop-down': '>=3.0.0',
						'@clayui/empty-state': '>=3.0.0',
						'@clayui/form': '>=3.0.0',
						'@clayui/icon': '>=3.0.0',
						'@clayui/label': '>=3.0.0',
						'@clayui/layout': '>=3.0.0',
						'@clayui/link': '>=3.0.0',
						'@clayui/list': '>=3.0.0',
						'@clayui/loading-indicator': '>=3.0.0',
						'@clayui/management-toolbar': '>=3.0.0',
						'@clayui/modal': '>=3.0.0',
						'@clayui/multi-select': '>=3.0.0',
						'@clayui/multi-step-nav': '>=3.0.0',
						'@clayui/nav': '>=3.0.0',
						'@clayui/navigation-bar': '>=3.0.0',
						'@clayui/pagination': '>=3.0.0',
						'@clayui/pagination-bar': '>=3.0.0',
						'@clayui/panel': '>=3.0.0',
						'@clayui/popover': '>=3.0.0',
						'@clayui/progress-bar': '>=3.0.0',
						'@clayui/shared': '>=3.0.0',
						'@clayui/slider': '>=3.0.0',
						'@clayui/sticker': '>=3.0.0',
						'@clayui/table': '>=3.0.0',
						'@clayui/tabs': '>=3.0.0',
						'@clayui/time-picker': '>=3.0.0',
						'@clayui/tooltip': '>=3.0.0',
						'@clayui/upper-toolbar': '>=3.0.0',
						clay: '>=2.9.0',
						'clay-alert': '>=2.9.0',
						'clay-autocomplete': '>=2.9.0',
						'clay-badge': '>=2.9.0',
						'clay-button': '>=2.9.0',
						'clay-card': '>=2.9.0',
						'clay-card-grid': '>=2.9.0',
						'clay-checkbox': '>=2.9.0',
						'clay-collapse': '>=2.9.0',
						'clay-component': '>=2.9.0',
						'clay-data-provider': '>=2.9.0',
						'clay-dataset-display': '>=2.9.0',
						'clay-dropdown': '>=2.9.0',
						'clay-icon': '>=2.9.0',
						'clay-label': '>=2.9.0',
						'clay-link': '>=2.9.0',
						'clay-list': '>=2.9.0',
						'clay-loading-indicator': '>=2.9.0',
						'clay-management-toolbar': '>=2.9.0',
						'clay-modal': '>=2.9.0',
						'clay-multi-select': '>=2.9.0',
						'clay-navigation-bar': '>=2.9.0',
						'clay-pagination': '>=2.9.0',
						'clay-pagination-bar': '>=2.9.0',
						'clay-portal': '>=2.9.0',
						'clay-progress-bar': '>=2.9.0',
						'clay-radio': '>=2.9.0',
						'clay-select': '>=2.9.0',
						'clay-sticker': '>=2.9.0',
						'clay-table': '>=2.9.0',
						'clay-tooltip': '>=2.9.0',
					},
				},
			},
			exclude: {
				'*': ['**/tests/**/*', '**/test/**/*', '**/__tests__/**/*'],
				'@babel/code-frame': true,
				'@babel/generator': true,
				'@babel/helper-annotate-as-pure': true,
				'@babel/helper-builder-binary-assignment-operator-visitor': true,
				'@babel/helper-call-delegate': true,
				'@babel/helper-define-map': true,
				'@babel/helper-explode-assignable-expression': true,
				'@babel/helper-function-name': true,
				'@babel/helper-get-function-arity': true,
				'@babel/helper-hoist-variables': true,
				'@babel/helper-member-expression-to-functions': true,
				'@babel/helper-module-imports': true,
				'@babel/helper-module-transforms': true,
				'@babel/helper-optimise-call-expression': true,
				'@babel/helper-plugin-utils': true,
				'@babel/helper-regex': true,
				'@babel/helper-remap-async-to-generator': true,
				'@babel/helper-replace-supers': true,
				'@babel/helper-simple-access': true,
				'@babel/helper-split-export-declaration': true,
				'@babel/helper-wrap-function': true,
				'@babel/highlight': true,
				'@babel/parser': true,
				'@babel/plugin-proposal-async-generator-functions': true,
				'@babel/plugin-proposal-json-strings': true,
				'@babel/plugin-proposal-object-rest-spread': true,
				'@babel/plugin-proposal-optional-catch-binding': true,
				'@babel/plugin-proposal-unicode-property-regex': true,
				'@babel/plugin-syntax-async-generators': true,
				'@babel/plugin-syntax-json-strings': true,
				'@babel/plugin-syntax-object-rest-spread': true,
				'@babel/plugin-syntax-optional-catch-binding': true,
				'@babel/plugin-transform-arrow-functions': true,
				'@babel/plugin-transform-async-to-generator': true,
				'@babel/plugin-transform-block-scoped-functions': true,
				'@babel/plugin-transform-block-scoping': true,
				'@babel/plugin-transform-classes': true,
				'@babel/plugin-transform-computed-properties': true,
				'@babel/plugin-transform-destructuring': true,
				'@babel/plugin-transform-dotall-regex': true,
				'@babel/plugin-transform-duplicate-keys': true,
				'@babel/plugin-transform-exponentiation-operator': true,
				'@babel/plugin-transform-for-of': true,
				'@babel/plugin-transform-function-name': true,
				'@babel/plugin-transform-literals': true,
				'@babel/plugin-transform-modules-amd': true,
				'@babel/plugin-transform-modules-commonjs': true,
				'@babel/plugin-transform-modules-systemjs': true,
				'@babel/plugin-transform-modules-umd': true,
				'@babel/plugin-transform-named-capturing-groups-regex': true,
				'@babel/plugin-transform-new-target': true,
				'@babel/plugin-transform-object-super': true,
				'@babel/plugin-transform-parameters': true,
				'@babel/plugin-transform-regenerator': true,
				'@babel/plugin-transform-shorthand-properties': true,
				'@babel/plugin-transform-spread': true,
				'@babel/plugin-transform-sticky-regex': true,
				'@babel/plugin-transform-template-literals': true,
				'@babel/plugin-transform-typeof-symbol': true,
				'@babel/plugin-transform-unicode-regex': true,
				'@babel/preset-env': true,
				'@babel/template': true,
				'@babel/traverse': true,
				'@babel/types': true,
				'ansi-styles': true,
				bootstrap: true,
				browserslist: true,
				'caniuse-lite': true,
				chalk: true,
				commander: true,
				'electron-to-chromium': true,
				lodash: true,
				'regenerate-unicode-properties': true,
				'regenerator-transform': true,
				'regexp-tree': true,
				rw: true,
				semver: true,
				'source-map': true,
			},
		},
	},
	federation: {
		mode: 'disabled',
		remotes: [
			'frontend-js-components-web',
			'frontend-js-metal-web',
			{
				name: '@liferay/frontend-js-react-web',
				webContextPath: 'frontend-js-react-web',
			},
			'frontend-js-spa-web',
			'frontend-js-web',
			{
				name: '@liferay/frontend-taglib',
				webContextPath: 'frontend-taglib',
			},
			'frontend-taglib-chart',
			'frontend-taglib-clay',
		],
		shared: [
			'@clayui/alert',
			'@clayui/autocomplete',
			'@clayui/badge',
			'@clayui/breadcrumb',
			'@clayui/button',
			'@clayui/card',
			'@clayui/charts',
			'@clayui/color-picker',
			'@clayui/css',
			'@clayui/data-provider',
			'@clayui/date-picker',
			'@clayui/drop-down',
			'@clayui/empty-state',
			'@clayui/form',
			'@clayui/icon',
			'@clayui/label',
			'@clayui/layout',
			'@clayui/link',
			'@clayui/list',
			'@clayui/loading-indicator',
			'@clayui/management-toolbar',
			'@clayui/modal',
			'@clayui/multi-select',
			'@clayui/multi-step-nav',
			'@clayui/nav',
			'@clayui/navigation-bar',
			'@clayui/pagination',
			'@clayui/pagination-bar',
			'@clayui/panel',
			'@clayui/popover',
			'@clayui/progress-bar',
			'@clayui/shared',
			'@clayui/slider',
			'@clayui/sticker',
			'@clayui/table',
			'@clayui/tabs',
			'@clayui/time-picker',
			'@clayui/tooltip',
			'@clayui/upper-toolbar',
			'classnames',
			'clay',
			'clay-alert',
			'clay-autocomplete',
			'clay-badge',
			'clay-button',
			'clay-card',
			'clay-card-grid',
			'clay-checkbox',
			'clay-collapse',
			'clay-component',
			'clay-data-provider',
			'clay-dataset-display',
			'clay-dropdown',
			'clay-icon',
			'clay-label',
			'clay-link',
			'clay-list',
			'clay-loading-indicator',
			'clay-management-toolbar',
			'clay-modal',
			'clay-multi-select',
			'clay-navigation-bar',
			'clay-pagination',
			'clay-pagination-bar',
			'clay-portal',
			'clay-progress-bar',
			'clay-radio',
			'clay-select',
			'clay-sticker',
			'clay-table',
			'clay-tooltip',
			'formik',
			'incremental-dom',
			'incremental-dom-string',
			'lodash.escape',
			'lodash.groupby',
			'lodash.isequal',
			'lodash.memoize',
			'lodash.unescape',
			'metal',
			'metal-affix',
			'metal-ajax',
			'metal-anim',
			'metal-aop',
			'metal-assertions',
			'metal-clipboard',
			'metal-component',
			'metal-debounce',
			'metal-dom',
			'metal-drag-drop',
			'metal-events',
			'metal-incremental-dom',
			'metal-jsx',
			'metal-key',
			'metal-keyboard-focus',
			'metal-multimap',
			'metal-pagination',
			'metal-path-parser',
			'metal-position',
			'metal-promise',
			'metal-router',
			'metal-scrollspy',
			'metal-soy',
			'metal-soy-bundle',
			'metal-state',
			'metal-storage',
			'metal-structs',
			'metal-throttle',
			'metal-toggler',
			'metal-uri',
			'metal-useragent',
			'metal-web-component',
			'prop-types',
			'querystring',
			'react',
			'react-dnd',
			'react-dnd-html5-backend',
			'react-dom',
			'svg4everybody',
			'uuid',
			'xss-filters',
		],
	},
	global: {
		check: CHECK_AND_FIX_GLOBS,
		fix: CHECK_AND_FIX_GLOBS,
	},
};
