/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataLimitEntry service. Represents a row in the &quot;DataLimitEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.DataLimitEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.DataLimitEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DataLimitEntry
 * @generated
 */
@ProviderType
public interface DataLimitEntryModel
	extends AuditedModel, BaseModel<DataLimitEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data limit entry model instance should use the {@link DataLimitEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this data limit entry.
	 *
	 * @return the primary key of this data limit entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data limit entry.
	 *
	 * @param primaryKey the primary key of this data limit entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data limit entry ID of this data limit entry.
	 *
	 * @return the data limit entry ID of this data limit entry
	 */
	public long getDataLimitEntryId();

	/**
	 * Sets the data limit entry ID of this data limit entry.
	 *
	 * @param dataLimitEntryId the data limit entry ID of this data limit entry
	 */
	public void setDataLimitEntryId(long dataLimitEntryId);

	/**
	 * Returns the company ID of this data limit entry.
	 *
	 * @return the company ID of this data limit entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this data limit entry.
	 *
	 * @param companyId the company ID of this data limit entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this data limit entry.
	 *
	 * @return the user ID of this data limit entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this data limit entry.
	 *
	 * @param userId the user ID of this data limit entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this data limit entry.
	 *
	 * @return the user uuid of this data limit entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this data limit entry.
	 *
	 * @param userUuid the user uuid of this data limit entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this data limit entry.
	 *
	 * @return the user name of this data limit entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this data limit entry.
	 *
	 * @param userName the user name of this data limit entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this data limit entry.
	 *
	 * @return the create date of this data limit entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this data limit entry.
	 *
	 * @param createDate the create date of this data limit entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this data limit entry.
	 *
	 * @return the modified date of this data limit entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this data limit entry.
	 *
	 * @param modifiedDate the modified date of this data limit entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}