/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.view.state.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FVSActiveEntry service. Represents a row in the &quot;FVSActiveEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.frontend.view.state.model.impl.FVSActiveEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.frontend.view.state.model.impl.FVSActiveEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FVSActiveEntry
 * @generated
 */
@ProviderType
public interface FVSActiveEntryModel
	extends BaseModel<FVSActiveEntry>, ContainerModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fvs active entry model instance should use the {@link FVSActiveEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this fvs active entry.
	 *
	 * @return the primary key of this fvs active entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fvs active entry.
	 *
	 * @param primaryKey the primary key of this fvs active entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this fvs active entry.
	 *
	 * @return the mvcc version of this fvs active entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this fvs active entry.
	 *
	 * @param mvccVersion the mvcc version of this fvs active entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this fvs active entry.
	 *
	 * @return the uuid of this fvs active entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this fvs active entry.
	 *
	 * @param uuid the uuid of this fvs active entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the fvs active entry ID of this fvs active entry.
	 *
	 * @return the fvs active entry ID of this fvs active entry
	 */
	public long getFvsActiveEntryId();

	/**
	 * Sets the fvs active entry ID of this fvs active entry.
	 *
	 * @param fvsActiveEntryId the fvs active entry ID of this fvs active entry
	 */
	public void setFvsActiveEntryId(long fvsActiveEntryId);

	/**
	 * Returns the company ID of this fvs active entry.
	 *
	 * @return the company ID of this fvs active entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this fvs active entry.
	 *
	 * @param companyId the company ID of this fvs active entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this fvs active entry.
	 *
	 * @return the user ID of this fvs active entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this fvs active entry.
	 *
	 * @param userId the user ID of this fvs active entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this fvs active entry.
	 *
	 * @return the user uuid of this fvs active entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this fvs active entry.
	 *
	 * @param userUuid the user uuid of this fvs active entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this fvs active entry.
	 *
	 * @return the user name of this fvs active entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this fvs active entry.
	 *
	 * @param userName the user name of this fvs active entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this fvs active entry.
	 *
	 * @return the create date of this fvs active entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this fvs active entry.
	 *
	 * @param createDate the create date of this fvs active entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this fvs active entry.
	 *
	 * @return the modified date of this fvs active entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this fvs active entry.
	 *
	 * @param modifiedDate the modified date of this fvs active entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fvs entry ID of this fvs active entry.
	 *
	 * @return the fvs entry ID of this fvs active entry
	 */
	public long getFvsEntryId();

	/**
	 * Sets the fvs entry ID of this fvs active entry.
	 *
	 * @param fvsEntryId the fvs entry ID of this fvs active entry
	 */
	public void setFvsEntryId(long fvsEntryId);

	/**
	 * Returns the clay data set display ID of this fvs active entry.
	 *
	 * @return the clay data set display ID of this fvs active entry
	 */
	@AutoEscape
	public String getClayDataSetDisplayId();

	/**
	 * Sets the clay data set display ID of this fvs active entry.
	 *
	 * @param clayDataSetDisplayId the clay data set display ID of this fvs active entry
	 */
	public void setClayDataSetDisplayId(String clayDataSetDisplayId);

	/**
	 * Returns the plid of this fvs active entry.
	 *
	 * @return the plid of this fvs active entry
	 */
	public long getPlid();

	/**
	 * Sets the plid of this fvs active entry.
	 *
	 * @param plid the plid of this fvs active entry
	 */
	public void setPlid(long plid);

	/**
	 * Returns the portlet ID of this fvs active entry.
	 *
	 * @return the portlet ID of this fvs active entry
	 */
	@AutoEscape
	public String getPortletId();

	/**
	 * Sets the portlet ID of this fvs active entry.
	 *
	 * @param portletId the portlet ID of this fvs active entry
	 */
	public void setPortletId(String portletId);

	/**
	 * Returns the container model ID of this fvs active entry.
	 *
	 * @return the container model ID of this fvs active entry
	 */
	@Override
	public long getContainerModelId();

	/**
	 * Sets the container model ID of this fvs active entry.
	 *
	 * @param containerModelId the container model ID of this fvs active entry
	 */
	@Override
	public void setContainerModelId(long containerModelId);

	/**
	 * Returns the container name of this fvs active entry.
	 *
	 * @return the container name of this fvs active entry
	 */
	@Override
	public String getContainerModelName();

	/**
	 * Returns the parent container model ID of this fvs active entry.
	 *
	 * @return the parent container model ID of this fvs active entry
	 */
	@Override
	public long getParentContainerModelId();

	/**
	 * Sets the parent container model ID of this fvs active entry.
	 *
	 * @param parentContainerModelId the parent container model ID of this fvs active entry
	 */
	@Override
	public void setParentContainerModelId(long parentContainerModelId);

}